config/routes.rb
Rails.application.routes.draw do

  
  
  
  resources :scores do 
    collection do 
      get :maintenance 
      get :franchisee
    end
  end

  resources :visits
  resources :maintenance_officers do 
     collection do 
      get :deployed
      get :suspended
      get :terminated
    end

    member do 
      get :accept 
      get :decline
      get :deploy
      post :deploy_maintenance_officer
      get :suspend
      get :terminate
      get :reactivate
      get :password_reset
    end
  end

  resources :countries do
    resources :districts do 
      resources :towns
    end
  end
  resources :officers do 
    collection do 
      get :deployed
      get :suspended
      get :terminated
    end

    member do 
      get :accept 
      get :decline
      get :deploy
      post :deploy_officer
      get :suspend
      get :terminate
      get :reactivate
      get :password_reset
    end

    resources :agents do 
      resources :reviews
    end
  end
  get '/reviews/:kiosk_id/officer/:id' => "officers#reviews" ,as: :show_review

 #FOR AJAX REQUESTS 
 get '/listingtowns' => 'officers#listings_towns' 
 get '/listingdistricts' => 'officers#listings_districts' 
  
  root 'sessions#new'

  match '/ChangePassword' => 'sessions#change_admin_pin', via: [:post]

  match '/ActivatePhone' => 'users#activatePhone', via: [:get, :post]
  match '/DeActivatePhone' => 'users#deActivatePhone', via: [:get, :post]
  match '/UserSearch' => 'users#searchByPhoneOrName', via: [:get, :post]
  
  match '/search_usr/update' => 'search_usr#new', :status =>"update", via: [:get, :post]
  match '/search_usr/suspend' => 'search_usr#new', :status =>"suspend", via: [:get, :post]
  match '/search_usr/delete' => 'search_usr#new', :status =>"delete", via: [:get, :post] 
  match '/search_usr/agent_profile' => 'search_usr#new', :status =>"agent_profile", via: [:get, :post] 
  
  match 'users/user_role' => 'users#user_role', via: [:get, :post]
  
  match '/ServiceSettings' => 'services_setting#index', via: [:get, :post]
  match '/EnableServiceSettings' => 'services_setting#enable', via: [:post]
  match '/DisableServicesSettings' => 'services_setting#disable', via: [:get, :post]
  match '/ViewThreshold' => 'services_setting#threshold', via: [:get, :post]
  match '/SetThreshold' => 'services_setting#setThreshold', via: [:get, :post]
  
  match '/CommissionPayment' => 'commission_payment#index', via: [:get, :post]
  match '/search_commission_payment' => 'commission_payment#search', via: [:get, :post]
  match '/pay_commission' => 'commission_payment#payCommission', via: [:get, :post]
  
  match '/TransactionHistory' => 'txn_history#index', via: [:get,:post]
 
  match '/PenaltyDetails' => 'penalty_report#searchPenaltyDetails', via: [:get,:post]

  match '/ProfitLoseDetails' => 'profit_lose_report#searchProfitLoseDetails', via: [:get,:post]

  match '/TaxDetails' => 'tax_report#searchTaxDeductDetails', via: [:get,:post]
  
  match '/CommissionPaymentDetails' => 'commission_payment_report#searchCommissionPaymentDetails', via: [:get,:post]

  match '/MFCashDeposit' => 'cash_deposit#index', via: [:get,:post]
  match '/MFCashDepositSearch' => 'cash_deposit#searchMF', via: [:get,:post]
  match '/MFCashDepositConfirm' => 'cash_deposit#depositFloat', via: [:post]

  match '/SearchNamePayment' => 'cash_payment#search_name', via: [:get,:post]
  match '/Reimbursement' => 'cash_payment#payment', via: [:post]

  match '/SearchUserName' => 'search_usr#search_name', via: [:get,:post]

  match '/CheckUserName' => 'reset_password#search_name', via: [:get,:post]
 
  match '/TaxConfiguration' => 'tax_configuration#index', via: [:get,:post]
  match '/TaxSetup' => 'tax_configuration#new',via: [:get,:post]
  match '/CreateTaxSetup' =>'tax_configuration#create', via: [:post]
  
  match '/PDFDownload' => 'pdf_generator#index', via: [:get,:post]

  match '/InitiateTxnRollback' => 'txn_rollback_initiate#index', via: [:get,:post]
  match '/InitiatedTxnRollback' => 'txn_rollback_initiate#initiateTxnRollback', via: [:get,:post] 
  match '/InitiatedTxnRollbackConfirm' => 'txn_rollback_initiate#initiatedTxnRollbackConfirm', via: [:get,:post]
  
  match '/ApproveTxnRollback' => 'txn_rollback_approve#index', via: [:get,:post]
  match '/ApproveSingleTxnRollback' => 'txn_rollback_approve#approveSingleTxn', via: [:get,:post]
  match '/ApprovedTxnRollbackConfirm' => 'txn_rollback_approve#approveTxnRollbackConfirm', via: [:get,:post]

  match '/CreditFeeSetup' => 'credit_fee_setup#index', via: [:get,:post]
  match '/CreditSetupDetails' => 'credit_fee_setup#getCreditDetails', via: [:get,:post]
  match '/CreditSetupConfirm' => 'credit_fee_setup#setupCredit', via: [:get,:post]

  match '/CreditSuspend' => 'credit_suspend#index', via: [:get,:post]
  match '/CreditSuspendPhone' => 'credit_suspend#searchByPhone', via: [:get,:post]
  match '/CreditSuspendName' => 'credit_suspend#searchByName', via: [:get,:post]
  match '/CreditSuspendConfirm' => 'credit_suspend#suspendCredit', via: [:get,:post]

  match '/CreditApproval' => 'credit_approval#index', via: [:get,:post]
  match '/ViewCredit' => 'credit_approval#viewSingleCredit', via: [:get,:post]
  match '/ApprovedCredit' => 'credit_approval#approvedCredit', via: [:get,:post]

  match '/CreditReport' => 'credit_report#index', via: [:get,:post]

  match '/MFCommissionReport' => 'mf_commission_report#index', via: [:get,:post]
  match '/SingleMFCommissionReport' => 'mf_commission_report#singleUserReport', via: [:get,:post]
  
  match '/AredRevenueReport' => 'revenue#index', via: [:get,:post]

  match '/TerminateUser' => 'users#destroy', via: [:get,:post]

  match '/ValidateOTP' => 'sessions#validateOTP', via: [:get,:post] 

  match '/Announcements' => 'announcements#index', via: [:get,:post]
  match '/CreateAnnouncement' => 'announcements#createAnnouncement', via: [:get,:post]

  match '/LeasingFeeSetup' => 'leasing_fee_setup#index', via: [:get,:post]
  match '/NewLeasingFeeSetup' => 'leasing_fee_setup#new', via: [:get,:post]
  match '/CreateLeasingFeeSetup' => 'leasing_fee_setup#createLeasingFeeSetup', via: [:get,:post]

  match '/TrackCustomer' => 'track_customer#index', via: [:get,:post]  

  match '/AggregatorSignup' => 'aggregator#index', via: [:get,:post]  
  match '/NewAggregatorSignup' => 'aggregator#new', via: [:get,:post]
  match '/NewAggregatorCreate' => 'aggregator#create', via: [:get,:post]

  match '/AggregatorDeposit' => 'aggregator_deposit#index', via: [:get,:post]  
  match '/AggregatorDepositAmt' => 'aggregator_deposit#deposit', via: [:get,:post]

  match '/AggregatorReport' => 'aggregator_report#index', via: [:get,:post]  
  
  match '/AuditLogs' => 'audit_logs#index', via: [:get, :post]

  match '/ThirdPartyConfig' => 'third_party_config#index', via: [:get, :post]
  match '/ThirdPartyConfigSave' => 'third_party_config#updateConfigs', via: [:get, :post]

  match '/MFFeedbacks' => 'suggestions#index', via: [:get, :post]

  match '/MFPenalties' => 'mf_penalty#index', via: [:get, :post]
  match '/MFPenaltiesPhone' => 'mf_penalty#searchByPhone', via: [:get, :post]
  match '/MFPenaltiesName' => 'mf_penalty#searchByName', via: [:get, :post]
  match '/MFAddPenalties' => 'mf_penalty#addPenalty', via: [:get, :post]

  match '/PenaltySetup' => 'mf_penalty_fee_setup#index', via: [:get, :post]
  match '/NewPenaltySetup' => 'mf_penalty_fee_setup#new', via: [:get, :post]
  match '/CreatePenalty' => 'mf_penalty_fee_setup#create', via: [:get, :post]
  match '/DeletePenaltySetup' => 'mf_penalty_fee_setup#delete', via: [:get, :post]

  match '/SuspendUser' => 'users#suspend_account', via: [:get, :post]
  match '/TerminateUser' => 'users#destroy', via: [:get, :post]

  match '/APIKeyGeneration' => 'api_key#index', via: [:get, :post]
  match '/APIKeyGenerated' => 'api_key#generateKey', via: [:get, :post]

  match '/ServiceFees' => 'service_fees_setup#index', via: [:get, :post]
  match '/ServiceFeesNew' => 'service_fees_setup#new', via: [:get, :post]
  match '/ServiceFeesSetup' => 'service_fees_setup#create', via: [:get, :post]
  match '/ServiceFeesDetails' => 'service_fees_setup#show', via: [:get, :post]

  match '/MFProfile' => 'user_profiles#profile', via: [:get, :post]

  match '/AssignKiosk' => 'kiosks#index', via: [:get, :post]
  match '/NewKiosk' => 'kiosks#new', via: [:get, :post]
  match '/CreateKiosk' => 'kiosks#create', via: [:get, :post]
  match '/AssignNewKiosk' => 'kiosks#assign', via: [:get, :post]
  match '/AssignedNewKiosk' => 'kiosks#assigned', via: [:get, :post]
  match '/SearchKiosk' => 'kiosks#search', via: [:get, :post]
  get '/printcode/:id' => 'kiosks#print' ,as: :printcode
  match '/ReGenerateKioskQRCode' => 'kiosks#regenerate', via: [:get, :post]
  match '/DownloadKioskQRCode' => 'kiosks#downloadQRCode', via: [:get, :post]

  match '/ForgotPassword' => 'forgot_passowrd#index', via: [:get, :post]
  match '/ValidateForNewPassword' => 'forgot_passowrd#validate', via: [:get, :post]
  match '/ResetPasswordDetails' => 'forgot_passowrd#new', via: [:get, :post]
  match '/SetNewPassword' => 'forgot_passowrd#forgot', via: [:get, :post]

  match '/PaymentModes' => 'payment_modes#index', via: [:get, :post]
  match '/AddPaymentMode' => 'payment_modes#new', via: [:get, :post]
  match '/CreatePaymentMode' => 'payment_modes#create', via: [:get, :post]
  match '/DeletePaymentMode' => 'payment_modes#delete', via: [:get, :post]
  

  
  
  post 'users/new_role_save' => 'users#new_role_save'
  get 'users/:id/suspend_account' => 'users#suspend_account', as: :users_suspend_account
  get 'users/:id/suspend' => 'users#suspend', as: :users_susp
  get 'users/:id/delete_usr' => 'users#delete_usr', as: :users_del
  get "change_pin" => "sessions#change_pin", as: "change_pin"
  get "Dashboard" => "sessions#Dashboard", as: "Dashboard"
  post 'logout' => 'sessions#destroy', :as => :logout
  delete 'sessions' => 'sessions#destroy'
  get 'mtopup_history/new'
  get 'mtopup_history/new'

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :agent
  belongs_to :maintenance_officer
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:agent_id, :maintenance_officer_id, :reason, :fixed)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @visit.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h4>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :agent, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :agent, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :maintenance_officer, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :maintenance_officer, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :reason, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :reason, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fixed, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :fixed, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/visits/edit.html.erb
<div class="page-header">
  <%= link_to visits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @visit, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing visit</h1>
</div>

<%= render 'form' %>

app/views/visits/index.html.erb
<div class="page-header">
  <%= link_to new_visit_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Visit
  <% end %>
  <h1>Listing visits</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Agent</th>
            <th>Maintenance officer</th>
            <th>Reason</th>
            <th>Fixed</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @visits) do |visit| %>
            <td><%= visit.agent %></td>
            <td><%= visit.maintenance_officer %></td>
            <td><%= visit.reason %></td>
            <td><%= visit.fixed %></td>
            <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/visits/new.html.erb
<div class="page-header">
  <%= link_to visits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New visit</h1>
</div>

<%= render 'form' %>

app/views/visits/show.html.erb
<div class="page-header">
  <%= link_to visits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_visit_path(@visit), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show visit</h1>
</div>

<dl class="dl-horizontal">
  <dt>Agent:</dt>
  <dd><%= @visit.agent %></dd>

  <dt>Maintenance officer:</dt>
  <dd><%= @visit.maintenance_officer %></dd>

  <dt>Reason:</dt>
  <dd><%= @visit.reason %></dd>

  <dt>Fixed:</dt>
  <dd><%= @visit.fixed %></dd>

</dl>